### Obtener historial de chat (GET /api/v1/history)
GET http://localhost:3016/api/v1/history HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjU1NDRmN2Y5M2VkNWEzYjJiY2MzYyIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwidXNlcm5hbWUiOiJ1c3VhcmlvQWRtaW4iLCJyb2xlcyI6W3siX2lkIjoiNjdiMWY3ZjMwNGZiYTUzODZiNDY4NmE2IiwibmFtZSI6ImFkbWluIiwicGVybWlzc2lvbnMiOlsiYWRtaW5fZ3JhbnRlZCJdLCJjcmVhdGVkQXQiOiIyMDI1LTAyLTE2VDE0OjM2OjM1LjMyMVoiLCJ1cGRhdGVkQXQiOiIyMDI1LTAyLTE2VDE0OjM2OjM1LjMyMVoifV0sIm5hdGlvbmFsaXR5IjoiQXJnZW50aW5vIiwibG9jYWxpdHkiOiJDQUJBIiwiYWdlIjoyNSwiY2FwU2VyZXNBcnRlIjpmYWxzZSwiY2FwVGhyIjpmYWxzZSwiY2FwUGhyIjpmYWxzZSwiaWF0IjoxNzQ1NzIzMDg0LCJleHAiOjE3NDU3MzAyODR9.nvLiWjhAC-IXaYD7Z7vdZzf6aavjqd2_06DrPkxQT-E
Content-Type: application/json